truncate table address;
truncate table also_buy;
truncate table app_audit;
truncate table app_event;
truncate table cookie;
truncate table customer_attr_value;
truncate table favorite;
truncate table feedback;
truncate table product_rate_value;
truncate table product_review;
update product_stat set reviewCount=0,averageRate=0,buyCount=0;
truncate table review_vote;
truncate table shop_point;
truncate table shop_point_history;
truncate table shoppingcart;
truncate table shoppingcart_item;
truncate table shoppingcart_item_gc;
truncate table validation_session;
truncate table system_message;
truncate table system_queue;
truncate table wishlist_item;
truncate table wishlist;
delete from app_user where userType=0 and appuserId>1;
delete from attribute where attributeType =3;